### ISSUE TITLE
Project Update 1

### ISSUE THREAD

**Issue by pickettj** [pickettj/central_asia_gazetteer#2]
Not too much to report yet, other than settling on a weekly meeting time. Initial tasks will include drafting a schema, and more importantly deciding on achievable research goals.

Does anyone know of any model project websites that integrate a digital edition of a text with an interactive geographical component?

**Comment by engeljonathan98** [comment]
I haven't found any model sites at a brief glance, but I did find two papers that seem relevant.
They both concern a European Research Council-funded group of projects trying to map the English Lake District to literary descriptions of the area. I skimmed them both just now but I think they could be useful.

- The [first paper](https://e-space.mmu.ac.uk/579357/2/Spatializing%20and%20Analyzing%20Digital%20Texts.pdf) discusses the viability and methodology of this and similar projects. It calls this work "Geographical Text Analysis" (GTA), which seeks to combine "corpus linguistics" (essentially, the study of linguistics within large texts) and GIS by associating key terms with a gazetteer and then associating that gazetteer with a GIS. Since we're starting _with_ our gazetteer, this paper should be a good reference.

2) The [second](http://eprints.lancs.ac.uk/81425/1/Donaldson_et_al_Historical_Atlas.pdf) describes the actual details of the (ongoing) English Lakes Project and the results their mapping produced. Skimming it, thus far have created some form of heat map showing what adjectives were used to describe where. Might have some inspiration here for where we could take this.

**Comment by AncientGreekGeek** [comment]
This project sounds super interesting! Would you focus on the whole treatise or just a couple of section over the course of this semester? 

I found this website in which they created a map of Ancient Augustine Rome in which they include ancient literary references to locations in the map. I'm not sure this will be useful  but it could provide sort of a reference to how you could integrate the text with the map: http://digitalaugustanrome.org.  

Here's an article that describes how the digital map works: https://classicalstudies.org/scs-blog/scott-arcenas/review-digital-augustan-rome

**Comment by pickettj** [comment]
Great questions; realistically, I will probably not be able to transcribe and translate the entire thing by the end of the semester; probably it will just be a few provinces. But we are going to design the project to be scalable, so that we can add to it going forward.
