### ISSUE TITLE
Map won't load on map_test.xhtml

### ISSUE THREAD

**Issue by engeljonathan98** [pickettj/central_asia_gazetteer#24]
I've copied James's code into my map_test.xhtml file, placing the `<section>` describing the map inside my `<div id="pseudo-map">`. The map _did_ load correctly once but isn't now. Help??

**Comment by djbpitt** [comment]
@gabikeane @engeljonathan98 I’ve tagged Gabi on this because she knows more about it than I do, but I think that you need an *.html* (not *.xhtml*) extension if you’re loading some of the map libraries. The reason for this is that Obdurodon is configured to serve files with an *.html* extension with a different mimetype (*text/html*) than those with *.xhtml* (*application/xhtml+xml*). Most of the time that’s what you want, but if the mapping library requires *text/html*, you have to use the filename extension that supports it.

**Comment by gabikeane** [comment]
[What are MIME types?](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)

I agree with David that the issue is .xhtml vs. .html, but it's also slightly more complicated than that. See the above link to read more about why they matter. Many servers just render .xhtml the same way that they render .html (because the filetype doesn't actually matter, the MIME type does). If I'm not mistaken, Obdurodon sees .xhtml and derives the MIME type from that, thus parsing your JavaScript in a way that makes error messages pop up.

As I wrote in a previous [response](https://github.com/pickettj/central_asia_gazetteer/issues/19#issuecomment-468696126) issue, the way we figure this out is by checking the console.

**Comment by djbpitt** [comment]
@gabikeane @engeljonathan98 As Gabi writes, Obdurodon maps from the filename extension to the mime type. The mapping table can vary from server to server; I set up Obdurodon this way to make it possible to serve both types of documents, anticipating that we might need the two for different purposes or in different contexts.

**Comment by engeljonathan98** [comment]
If this is the case, what do you wager is the best solution? Just writing things as HTMLs instead of XHTMLs?

**Comment by engeljonathan98** [comment]
This also doesn't explain the fact that I can James's About page, which is also XHTML, to function on my internal machine, which I'm running all of these on.
