### ISSUE TITLE
HTML to XHTML conversion weirdness

### ISSUE THREAD

**Issue by engeljonathan98** [pickettj/central_asia_gazetteer#28]
[Per Gabi's suggestion](https://github.com/pickettj/central_asia_gazetteer/issues/19#issuecomment-468696126), I tried testing the bukhara_protectorate_map.js script on an HTML page instead of an XHTML page. Specifically, I simply converted the file type of map_test.xhtml (where I've been working on our map interface) to .html.

Hey! The circle and the marker appear now! Yay!

However: the styling seems off? Now, the textbox and buttons -- which are visible on the map_test.xhtml file on which the circle and marker don't work -- don't appear. Per the developer's console of my browser, they are being drawn _underneath_ the map, but _only in the HTML file and not the XHTML equivalent that has identical code_.

So: what? Clearly there seems to be some difference in the styling but I'm not sure how that would arise. Both files are on the same level of our directory hierarchy so it shouldn't be an issue of accessing stylesheets. Nor should elements overlap; in XHTML, they were always rendered a certain distance apart from one another.

**Comment by djbpitt** [comment]
@engeljonathan98 @gabikeane The difference between filenames that end in _.html_ and those that end in _.xhtml_ on Obdurodon is that the former are served with the mimetype `text/html` and the latter with the mimetype `application/xhtml+xml`. This is an Obdurodon configuration; other hosts may follow different practice. I configured the server that way so that developers would have access to (and control over) both options. If you check the headers in the browser debugging interface, the mimetype will be reported there. 

Although the source file for your _.html_ and _.xhtml_ versions might be identical, the mimetype is part of the picture, and may affect (= seems to affect) how they are rendered in the browser. The different mimetypes can cause a different DOM representation to be built, which means that the CSS will interact with it differently. There are also a few differences in boilerplate. For example, XML files may begin with the XML declaration (technically optional), but HTML files that are not served as XML shouldn’t because pages served with mimetype `text/html` are not parsed in the browser as XML. If you haven’t tried this already, you can validate your pages at https://validator.w3.org and see whether it reports anything unexpected? Gabi, does Leaflet have any odd expectations about namespaces or doctype declarations or anything like that? Or about raw ampersands as opposed to character entities?

**Comment by engeljonathan98** [comment]
I changed a `<div>` from self-closing to having an end tag and now everything works. Thanks for shooting me the Validator.`
