### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by pickettj** [pickettj/central_asia_gazetteer#44]
For the English reading view, I have a CSS working that allows mouse-over gloss. The CSS works just fine with the [mock-up](https://github.com/pickettj/central_asia_gazetteer/blob/master/reading_view.xhtml); but when I run [XSLT](https://github.com/pickettj/central_asia_gazetteer/blob/master/xslt/reading_view_english.xsl) on the actual text, using the exact same formatting, the CSS [won't work](https://github.com/pickettj/central_asia_gazetteer/blob/master/xslt/xslt_output.xhtml) for some reason.

Surely this is some minor, stupid error on my part, but it's holding me back...

**Comment by zme1** [comment]
@pickettj I’ll be back in front of my computer in a couple hours, and I’ll poke around if you haven’t figured it out by then!

**Comment by djbpitt** [comment]
@pickettj A few thoughts:

1. Compare the XHTML output of the XSLT transformation to the mockup, especially with attention to the `<link>` elements that points to your CSS and the elements that respond to `hover`. Since the files are small, you can do that by just looking, but \<oXygen/\> also has an *XML diff* (file differencing) utility under the Tools menu, which will find and highlight the differences. It has an option to tell it to ignore whitespace differences, so that you won’t be distracted by differences in pretty-printing, which typically are not informational.
1. Are the XHTML output of the transformation and the mockup in the same place, so that they can both find the CSS at the same relative path location?
1. Are both files the same mime type, that is, both XHTML or both HTML?

**Comment by pickettj** [comment]
Thanks @djbpitt! It was the relative path issue. Doh...
